functions:
- cleanupVisits:
    path: /cleanupVisits
    function: cleanupVisits
    eventName: 'cleanup'

serverless:
  basePath: /${BRANCH}
  port: 3006

invoke:
  local:
    params:
      apiVersion: 2015-03-31
      endpoint: http://localhost:3013
    functions:
      testResults:
        name: cvs-svc-test-results
        mock: tests/resources/test-results-200-response.json
      activities:
        name: cvs-svc-activities
        mock: tests/resources/activities-response.json
  remote:
    params:
      apiVersion: 2015-03-31
    functions:
      testResults:
        name: test-results-${BRANCH}
      activities:
        name: activities-${BRANCH}
notify:
  api_key:
